# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FTKJ' do
 
pod 'AFNetworking'
    
 pod 'SDWebImage'
 
 pod 'MBProgressHUD'
 
 pod 'SDCycleScrollView'
 
 pod 'IQKeyboardManager'
 
 pod 'TZImagePickerController'
 
 pod 'MJRefresh'
 
 pod 'MJExtension'
  
 pod 'Reachability'
 
 pod 'SSKeychain'
 
 pod 'PinYin4Objc'
 
 pod 'AFNetworking'

# pod 'WechatOpenSDK'

 pod 'mob_sharesdk'

 pod 'FMDB', '~> 2.7.2'
 
 # UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
 pod 'mob_sharesdk/ShareSDKUI'
 
 # 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
 pod 'mob_sharesdk/ShareSDKPlatforms/QQ'
 pod 'mob_sharesdk/ShareSDKPlatforms/SinaWeibo'
 pod 'mob_sharesdk/ShareSDKPlatforms/WeChatFull'
 pod 'MOFSPickerManager'




end
